repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort
        pass_filenames: false
        entry: poetry run isort .
        language: python

      - id: black
        name: black
        pass_filenames: false
        entry: poetry run black .
        language: python

      - id: ruff
        name: ruff
        pass_filenames: false
        entry: poetry run ruff --fix .
        language: python
