services:
  main:
    build: .
    container_name: core
    network_mode: host
    volumes:
      - /home/exenifix/core-data/backgrounds:/app/backgrounds
      - /home/exenifix/core-data/logs:/app/logs
    environment:
      - TOKEN
      - DATABASE=core
      - PASSWORD
      - USER=core
      - GOOGLE_API_KEY
    restart: always
