name: deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build and Run
        run: docker-compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Display Logs
        run: python3 -m exendlr core "bot is ready!"

      - name: Cleanup Unused Images
        run: docker image prune -f
